// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
//
// Custom CS PostProcessing Shader

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Public/Platform.ush"

#include "/Engine/Private/SSRT/SSRTRayCast.ush"

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;
Texture2D SceneDepth;

Texture2DArray<float4> ProbeCascadesRead;
RWTexture2DArray<float4> ProbeCascades;

Texture2D HZB;
float4 HZBUvFactorAndInv;



SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)
SCREEN_PASS_TEXTURE_VIEWPORT(TraceViewport)
uint Cascade;
uint CascadeCount;
uint BaseRayCount;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)] void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	uint2 PixelId = DispatchThreadId + SceneColorViewport_ViewportMin;
	// Check that we are in scope
	if (any(PixelId >= SceneColorViewport_Extent))
	{
		return;
	}
    float ShortestSide = min(SceneColorViewport_ViewportSize.x, SceneColorViewport_ViewportSize.y);

	int RayCount = pow(BaseRayCount, 1 + Cascade);
	float SqrtBase = sqrt(float(BaseRayCount));
	float Spacing = pow(SqrtBase, Cascade);
	float2 Size = floor(SceneColorViewport_ViewportSize / Spacing);

	// Current probe
	float2 ProbeRelativePosition = DispatchThreadId % Size;
	float2 RayPos = min(floor(DispatchThreadId / Size), Spacing - 1.0);
	// Base index of the rays for knowing which angle to start
	float BaseIndex = float(BaseRayCount) * (RayPos.x + (Spacing * RayPos.y));

	float2 ProbeCenter = (ProbeRelativePosition + 0.5) * Spacing + SceneColorViewport_ViewportMin;

	float IntervalStart = Cascade == 0.0 ? 0.0 : (pow(BaseRayCount, Cascade - 1.0)) / ShortestSide;
	float IntervalLength = pow(BaseRayCount, Cascade) / ShortestSide;
	float IntervalEnd = IntervalStart + IntervalLength;

	float4 Radiance = float4(0.0, 0.0, 0.0, 0.0);


	// March SceneColor
	for (int i = 0; i < BaseRayCount; i++)
	{
		float Index = BaseIndex + float(i);
		// Add 0.5 radians to avoid vertical angles
		float AngleStep = Index + 0.5;
		float Angle = ((2 * PI) / RayCount) * AngleStep;
		float2 RayDirection = float2(cos(Angle), -sin(Angle));

		float4 RadDelta = float4(0.0, 0.0, 0.0, 1.0);
        float2 StartPixel = ProbeCenter + RayDirection * (IntervalStart * ShortestSide);
        float2 EndPixel = ProbeCenter + RayDirection * (IntervalEnd * ShortestSide);
       
        float2 StartUV = (StartPixel - SceneColorViewport_ViewportMin) * SceneColorViewport_ViewportSizeInverse;
        float2 EndUV = (EndPixel - SceneColorViewport_ViewportMin) * SceneColorViewport_ViewportSizeInverse;

        float2 StartNDC = ViewportUVToScreenPos(StartUV);
        float2 EndNDC = ViewportUVToScreenPos(EndUV);

        float2 StartDepthUV = (StartPixel - SceneColorViewport_ViewportMin + View.ViewRectMin.xy)
                    * View.BufferSizeAndInvSize.zw;
        float Depth = SceneDepth.SampleLevel(GlobalBilinearClampedSampler, StartDepthUV, 0);

        const float ThicknessWorld = 20.0; // Approximate Thickness for blocking geo
        float LinearDepth = ConvertFromDeviceZ(Depth);

		// Do a screen space depth trace
		FSSRTRay Ray;
        Ray.CompareTolerance = abs(Depth - ConvertToDeviceZ(LinearDepth + ThicknessWorld));
		Ray.RayStartScreen = float3(StartNDC, Depth+ 0.0001);
        Ray.RayStepScreen = float3(EndNDC - StartNDC, 0.0);
        float3 DebugOutput;
		float3 HitUVz;
		float Level;
		bool bFoundHit;
		bool bUncertain;
        CastScreenSpaceRay(HZB, GlobalBilinearClampedSampler, 0, CreateDefaultCastSettings(), Ray, 0.0, 32, 0.0, HZBUvFactorAndInv, false, DebugOutput, HitUVz, Level, bFoundHit,
						   bUncertain);

        if (bFoundHit)
        {
            float2 HitViewportUV = HitUVz.xy * HZBUvFactorAndInv.zw;
			float2 HitBufferUV = (HitViewportUV + SceneColorViewport_UVViewportMin);
            float4 ColorSample = OriginalSceneColor.SampleLevel(GlobalBilinearClampedSampler, float2(HitBufferUV.xy), 0.0);
            RadDelta.rgb = float3(HitBufferUV.rg, 0.0)*0.2;
            RadDelta.rgb += ColorSample;
            RadDelta.a = 0.0;
        }
        else
        {
            RadDelta.a = 1.0;
        }

		if (Cascade < CascadeCount - 1 && RadDelta.a != 0.0 && 0)
		{
			// Merge upper cascade

			// The spacing between probes
			float UpperSpacing = pow(SqrtBase, Cascade + 1);
			// Grid of probes
			float2 UpperSize = floor(SceneColorViewport_ViewportSize / UpperSpacing);
			// Position of this probe
			float2 UpperPosition = float2(Index % UpperSpacing, floor(Index / UpperSpacing)) * UpperSize;

			float2 Offset = (ProbeRelativePosition + 0.5) / SqrtBase;
            float4 UpperCascade = ProbeCascadesRead.
            SampleLevel(
				GlobalBilinearClampedSampler, float3((UpperPosition + Offset + SceneColorViewport_ViewportMin) * SceneColorViewport_ExtentInverse, Cascade + 1),
				0.0);
            RadDelta.rgb += RadDelta.a * UpperCascade.rgb;
            RadDelta.a *= UpperCascade.a;
        }
		// Accumulate total radiance
		Radiance += RadDelta;
	}
	float4 Output = Radiance / float(BaseRayCount);
    
    ProbeCascades[uint3(PixelId, Cascade)] = Output;

    //float2 StartDepthUV = (ProbeCenter - SceneColorViewport_ViewportMin + View.ViewRectMin.xy)
    //                * View.BufferSizeAndInvSize.zw;
    //float Depth = SceneDepth.SampleLevel(GlobalBilinearClampedSampler, StartDepthUV, 0);
    //ProbeCascades[uint3(PixelId, Cascade)] = float4(float3(Depth, Depth, Depth), 1.0);

    //float2 HitBufferUV = ProbeCenter * SceneColorViewport_ViewportSizeInverse
    //               + SceneColorViewport_UVViewportMin;
    //float4 ColorSample = OriginalSceneColor.SampleLevel(GlobalBilinearClampedSampler, float2(HitBufferUV.xy), 0.0);
    //ProbeCascades[uint3(PixelId, Cascade)] = ColorSample;

	//ProbeCascades[uint3(PixelId, Cascade)] = float4(ProbeCenter * SceneColorViewport_ViewportSizeInverse,0.0,1.0);
}