// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;

RWTexture2DArray<float4> ProbeCascades;

uint2 Resolution;

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	// Check that we are in scope
    if (any(DispatchThreadId >= Resolution))
    {
        return;
    }
	
    // Calculate SampleUV with viewport parameters
    float2 sampleUV = ((DispatchThreadId + 0.5)) / float2(Resolution);

    // sample OriginalColor
    float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);

    // To test that everything is working, switch Red and Blue
    float4 OutputColor = float4(OriginalColor.z, OriginalColor.y, OriginalColor.x, OriginalColor.w);


    // Write output
    ProbeCascades[uint3(DispatchThreadId, 0)] = OutputColor;
}