#include "/Engine/Private/Common.ush"
#include "/Engine/Private/SceneTextureParameters.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingDeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingLightingCommon.ush"
#include "/Engine/Private/Random.ush"
#include "/Engine/Private/MonteCarlo.ush"
RaytracingAccelerationStructure TLAS;
RWTexture2D<float4> Output;
Texture2D SceneDepth;

#define R2_G  1.32471795724474602596f
#define R2_A1 0.754877666246692760050f  // 1 / g
#define R2_A2 0.569840290998053265911f  // 1 / g^2


float2 R2Sequence(uint n, float2 Offset)
{
	return frac(0.5f + float2(R2_A1, R2_A2) * (float)n + Offset);
}

RAY_TRACING_ENTRY_RAYGEN(MainRG)
{
	uint2 PixelCoord = DispatchRaysIndex().xy + View.ViewRectMin.xy;
	float2 UV = (PixelCoord + 0.5) * View.BufferSizeAndInvSize.zw;

	FGBufferData GBuffer = GetGBufferDataFromSceneTextures(UV);
	if (GBuffer.ShadingModelID == SHADINGMODELID_UNLIT)
	{
		return;
	}

	float DeviceZ = SceneDepth.Load(int3(PixelCoord, 0)).r;
	float3 TranslatedWorldPos = SvPositionToTranslatedWorld(float4(PixelCoord + 0.5, DeviceZ, 1.0));
	float3 N = GBuffer.WorldNormal;
	FRayDesc Ray;
	Ray.Origin = TranslatedWorldPos + N * 0.5;
	Ray.Direction = reflect(normalize(TranslatedWorldPos),
	                        N);
	Ray.TMin = 0.01;
	Ray.TMax = 100000.0;

	FRandomSequence RandSequence;
	RandomSequence_Initialize(RandSequence, PixelCoord, 0, View.StateFrameIndex, 1);

	FRayCone RayCone = (FRayCone)0;
	RayCone.SpreadAngle = View.EyeToPixelSpreadAngle;

	float3 Radiance = 0;

	float4 DirectionPDF = CosineSampleHemisphere(
		R2Sequence(PixelCoord.x + PixelCoord.y * View.BufferSizeAndInvSize.x, float2(0, 0)), N);
	Ray.Direction = reflect(normalize(TranslatedWorldPos), N);//DirectionPDF.xyz;

	FMaterialClosestHitPayload Payload = TraceRayAndAccumulateResults(
		Ray,
		TLAS,
		TLAS, // FarFieldTLAS, unused when ENABLE_FAR_FIELD_TRACING==0
		RAY_FLAG_CULL_BACK_FACING_TRIANGLES,
		RAY_TRACING_MASK_OPAQUE,
		RandSequence,
		PixelCoord,
		0.1, // ShadowMaxNormalBias
		100000.0, // MaxTraceDistance
		RAY_TRACING_SHADOWS_TYPE_HARD,
		RAY_TRACING_SHADOWS_TRANSLUCENCY_TYPE_OPAQUE,
		1, // ShouldDoDirectLighting
		1, // ShouldDoEmissiveAndIndirectLighting
		false, // bRayTraceSkyLightContribution
		false, // bDecoupleSampleGeneration
		false, // bIsCameraRay
		RayCone,
		true, // bEnableSkyLightContribution
		Radiance);

	if (Payload.IsMiss())
	{
		return;
	}


	Output[PixelCoord] += float4(Radiance * DirectionPDF.w, 1);
}
