#include "/Engine/Private/Common.ush"
#include "/Engine/Private/SceneTextureParameters.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingDeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingLightingCommon.ush"
#include "/Engine/Private/Random.ush"
#include "/Engine/Private/MonteCarlo.ush"
#include "RCHashTable.ush"
#include "RCCommon.ush"
RaytracingAccelerationStructure TLAS;
RWTexture2D<float4> Output;
Texture2D SceneDepth;

RWStructuredBuffer<uint4> TotalRadiance;
RWStructuredBuffer<uint> Weights;
RWStructuredBuffer<uint> BinCounts;
RWStructuredBuffer<uint> DepositCounts;

uint BaseDirections; // Currently assumed to be 32...
float NormalOffset;

static const uint NumCascades = 4;
static const float C0Len = 1.5958; // sqrt(2*4*4 / (4*PI)), hardcoded for 32 directions


RAY_TRACING_ENTRY_RAYGEN(MainRG)
{
	uint2 PixelCoord = DispatchRaysIndex().xy + View.ViewRectMin.xy;
	float2 UV = (PixelCoord + 0.5) * View.BufferSizeAndInvSize.zw;

	FGBufferData GBuffer = GetGBufferDataFromSceneTextures(UV);
	if (GBuffer.ShadingModelID == SHADINGMODELID_UNLIT)
	{
		return;
	}

	float DeviceZ = SceneDepth.Load(int3(PixelCoord, 0)).r;
	float3 TranslatedWorldPos = SvPositionToTranslatedWorld(float4(PixelCoord + 0.5, DeviceZ, 1.0));
	float3 N = GBuffer.WorldNormal;
	FRayDesc Ray;
	Ray.Origin = TranslatedWorldPos + N *NormalOffset;
	Ray.TMin = 0.1;
	Ray.TMax = 100000.0;

	float3 WorldPos = DFFastSubtractDemote(TranslatedWorldPos, PrimaryView.PreViewTranslation);
	float3 CameraPos = DFHackToFloat(PrimaryView.WorldCameraOrigin);

	uint64_t TopKey = MakeProbeKey(WorldPos, CameraPos);

	uint TopProbeIndex = MurmurFinalize32(uint(TopKey) ^ MurmurFinalize32(uint(TopKey >> 32)));
	bool InProbe = HashTableFind(TopKey, TopProbeIndex, 0);

	if (!InProbe)
	{
		//Shouldn't really be possible
		return;
	}
	uint TopSlotIndex = TopProbeIndex;
	uint BinIndex = 0;
	InterlockedAdd(BinCounts[TopSlotIndex], 1, BinIndex);

	FRandomSequence RandSequence;
	RandomSequence_Initialize(RandSequence, PixelCoord, BinIndex+1, 0, 1);

	FRayCone RayCone = (FRayCone)0;
	RayCone.SpreadAngle = View.
		EyeToPixelSpreadAngle;

	float3 Radiance = 0;

	//Add per probe hash to randomize it a bit so not all probes go into a similar direction on low samples
	float2 E = R2Sequence(BinIndex + 1);
	float3 Dir = UniformSampleSphere(E).xyz;
	Dir *= sign(dot(Dir, N));
	Ray.Direction = Dir.
		xyz;

	FMaterialClosestHitPayload Payload = TraceRayAndAccumulateResults(
		Ray,
		TLAS,
		TLAS, // FarFieldTLAS, unused when ENABLE_FAR_FIELD_TRACING==0
		RAY_FLAG_CULL_BACK_FACING_TRIANGLES,
		RAY_TRACING_MASK_OPAQUE,
		RandSequence,
		PixelCoord,
		0.1, // ShadowMaxNormalBias
		100000.0, // MaxTraceDistance
		RAY_TRACING_SHADOWS_TYPE_HARD,
		RAY_TRACING_SHADOWS_TRANSLUCENCY_TYPE_OPAQUE,
		1, // ShouldDoDirectLighting
		1, // ShouldDoEmissiveAndIndirectLighting
		false, // bRayTraceSkyLightContribution
		false, // bDecoupleSampleGeneration
		false, // bIsCameraRay
		RayCone,
		true, // bEnableSkyLightContribution
		Radiance);


	//Split ray into probe
	uint RayCascade = NumCascades - 1;
	if (Payload.IsHit())
	{
		uint Level = ComputeLevel(WorldPos, CameraPos);

		float FCascade = ceil(max(0.5 * log2(Payload.HitT / (C0Len * LevelVoxelSize(Level))), 0.0));
		RayCascade = min((uint)FCascade, NumCascades - 1);
	}


	//Fill into containing cascades

	for (
		uint Cascade = 0; Cascade <=
		RayCascade; ++Cascade)
	{
		uint64_t Key = MakeProbeKey(WorldPos, CameraPos);
		ProbeKeyInfo KeyData = UnpackProbeKey(Key);
		uint2 LevelRange;
		float2 LodWeights;
		ComputeLevelRange(WorldPos, CameraPos, LevelRange, LodWeights);

		for (
			uint Level = 0; Level < 2; ++Level)
		{
			uint64_t CascadeKey = PackProbeKey(KeyData.Cell >> (Cascade + Level), LevelRange[Level]);

			uint ProbeIndex = MurmurFinalize32(uint(CascadeKey) ^ MurmurFinalize32(uint(CascadeKey >> 32)));
			if (HashTableFind(CascadeKey, ProbeIndex, Cascade))
			{
				bool HitCascade = (Cascade == RayCascade);

				uint DirectionCount = BaseDirections << Cascade;

				uint CascadeIndex = Cascade * HashTableSize * BinsPerProbe(BaseDirections);
				uint SlotIndex = CascadeIndex + ProbeIndex * BinsPerProbe(DirectionCount) + DirToLinear(
					Dir.xyz, DirectionCount);
				float3 Rad = HitCascade ? float3(0,0,0) : Radiance * LodWeights[Level];
                uint PackedLodWeight = PackFloatUnsigned(LodWeights[Level]);
				//Pack to uints to use atomics
				InterlockedAdd(TotalRadiance[SlotIndex].x, PackFloatUnsigned(Rad.x));
				InterlockedAdd(TotalRadiance[SlotIndex].y, PackFloatUnsigned(Rad.y));
				InterlockedAdd(TotalRadiance[SlotIndex].z, PackFloatUnsigned(Rad.z));
				InterlockedAdd(TotalRadiance[SlotIndex].w, HitCascade ? 0u : PackedLodWeight); // Transmittance
				InterlockedAdd(Weights[SlotIndex], PackedLodWeight);
				InterlockedAdd(DepositCounts[Cascade * HashTableSize + ProbeIndex], PackedLodWeight);
			}
		}
	}
	//Output[PixelCoord] = float4(Radiance * 2*PI,1.0);
}
