#include "/Engine/Private/Common.ush"
#include "/Engine/Private/SceneTextureParameters.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingDeferredShadingCommon.ush"
#include "/Engine/Private/RayTracing/RayTracingLightingCommon.ush"
#include "/Engine/Private/Random.ush"
#include "/Engine/Private/MonteCarlo.ush"
#include "RCHashTable.ush"
#include "RCCommon.ush"
RaytracingAccelerationStructure TLAS;
RWTexture2D<float4> Output;
Texture2D SceneDepth;

RWStructuredBuffer<uint4> TotalRadiance;
RWStructuredBuffer<uint> Weights;

static const uint NumCascades = 4;
static const float C0Len = 1.5958; // sqrt(2*4*4 / (4*PI)), hardcoded for 32 directions


RAY_TRACING_ENTRY_RAYGEN(MainRG)
{
	uint2 PixelCoord = DispatchRaysIndex().xy + View.ViewRectMin.xy;
	float2 UV = (PixelCoord + 0.5) * View.BufferSizeAndInvSize.zw;

	FGBufferData GBuffer = GetGBufferDataFromSceneTextures(UV);
	if (GBuffer.ShadingModelID == SHADINGMODELID_UNLIT)
	{
		return;
	}

	float DeviceZ = SceneDepth.Load(int3(PixelCoord, 0)).r;
	float3 TranslatedWorldPos = SvPositionToTranslatedWorld(float4(PixelCoord + 0.5, DeviceZ, 1.0));
	float3 N = GBuffer.WorldNormal;
	FRayDesc Ray;
	Ray.Origin = TranslatedWorldPos + N * 0.5;
	Ray.TMin = 0.01;
	Ray.TMax = 100000.0;

	FRandomSequence RandSequence;
	RandomSequence_Initialize(RandSequence, PixelCoord, 0, View.StateFrameIndex, 1);

	FRayCone RayCone = (FRayCone)0;
	RayCone.SpreadAngle = View.EyeToPixelSpreadAngle;

	float3 Radiance = 0;

    //Current R2 Seq is based on pixel, but it should be counting up per probe at this worldpos
	float2 E = R2Sequence(PixelCoord.x + PixelCoord.y * View.BufferSizeAndInvSize.x + View.StateFrameIndex);
	float3 Dir = UniformSampleSphere(E).xyz;
	Dir *= sign(dot(Dir, N));
	Ray.Direction = Dir.xyz;

	FMaterialClosestHitPayload Payload = TraceRayAndAccumulateResults(
		Ray,
		TLAS,
		TLAS, // FarFieldTLAS, unused when ENABLE_FAR_FIELD_TRACING==0
		RAY_FLAG_CULL_BACK_FACING_TRIANGLES,
		RAY_TRACING_MASK_OPAQUE,
		RandSequence,
		PixelCoord,
		0.1, // ShadowMaxNormalBias
		100000.0, // MaxTraceDistance
		RAY_TRACING_SHADOWS_TYPE_HARD,
		RAY_TRACING_SHADOWS_TRANSLUCENCY_TYPE_OPAQUE,
		1, // ShouldDoDirectLighting
		1, // ShouldDoEmissiveAndIndirectLighting
		false, // bRayTraceSkyLightContribution
		false, // bDecoupleSampleGeneration
		false, // bIsCameraRay
		RayCone,
		true, // bEnableSkyLightContribution
		Radiance);

	float3 WorldPos = DFFastSubtractDemote(TranslatedWorldPos, PrimaryView.PreViewTranslation);
	float3 CameraPos = DFHackToFloat(PrimaryView.WorldCameraOrigin);

	//Split ray into probe
	uint RayCascade = NumCascades - 1;
	if (Payload.IsHit())
	{
		uint Level = ComputeLevel(WorldPos, CameraPos);

		float FCascade = ceil(max(0.5 * log2(Payload.HitT / (C0Len * LevelVoxelSize(Level))), 0.0));
		RayCascade = min((uint)FCascade, NumCascades - 1);
	}


	//Fill into containing cascades
	for (uint Cascade = 0; Cascade <= RayCascade; ++Cascade)
	{
		uint64_t Key = MakeProbeKey(WorldPos, CameraPos);
		ProbeKeyInfo KeyData = UnpackProbeKey(Key);
		uint64_t CascadeKey = PackProbeKey(KeyData.Cell >> Cascade, KeyData.Level);

		uint ProbeIndex = MurmurFinalize32(uint(CascadeKey) ^ MurmurFinalize32(uint(CascadeKey >> 32)));
		if (HashTableFind(CascadeKey, ProbeIndex, Cascade))
		{
			bool HitCascade = (Cascade == RayCascade);


uint SlotIndex = ProbeIndex * BinsPerProbe() + DirToLinear(Dir.xyz);
			float3 Rad = Radiance * 2*PI;
			//Pack to uints to use atomics
			InterlockedAdd(TotalRadiance[SlotIndex].x, PackFloatUnsigned(Rad.x));
			InterlockedAdd(TotalRadiance[SlotIndex].y, PackFloatUnsigned(Rad.y));
			InterlockedAdd(TotalRadiance[SlotIndex].z, PackFloatUnsigned(Rad.z));
            InterlockedAdd(TotalRadiance[SlotIndex].w, HitCascade ? 0u : 1u); // Transmittance
			InterlockedAdd(Weights[SlotIndex], 1);
		}
	}
}
