#define FLOAT_ATOMIC_PRECISION 0.00001
#define FLOAT_ATOMIC_INV_PRECISION (1/FLOAT_ATOMIC_PRECISION)

uint DirectionCount;

uint PackFloatUnsigned(float Value)
{
	return Value*FLOAT_ATOMIC_INV_PRECISION;
}

float UnpackFloatUnsigned(uint Packed)
{
    return Packed * FLOAT_ATOMIC_PRECISION;
}

static const float INV_TWO_PI = 0.15915494309189535;

float NextFloatDown(float x)
{
    return asfloat(asuint(x) - 1u);
}

float2 EncodeDir(float3 d)
{
    return float2(frac(atan2(d.y, d.x) * INV_TWO_PI), (d.z + 1.0) * 0.5);
}

uint2 QuantizeDir(float2 uv, uint2 gridSize)
{
    float2 s = float2(NextFloatDown(gridSize.x), NextFloatDown(gridSize.y));
    return (uint2) (uv * s);
}

uint Part1By1(uint x)
{
    x &= 0x0000FFFFu;
    x = (x ^ (x << 8)) & 0x00FF00FFu;
    x = (x ^ (x << 4)) & 0x0F0F0F0Fu;
    x = (x ^ (x << 2)) & 0x33333333u;
    x = (x ^ (x << 1)) & 0x55555555u;
    return x;
}

uint EncodeMorton2(uint2 v)
{
    return Part1By1(v.x) | (Part1By1(v.y) << 1);
}


uint BinsPerProbe()
{
    return DirectionCount * 2 * DirectionCount;
}
uint DirToLinear(float3 dir)
{
    uint2 g = uint2(DirectionCount << 1, DirectionCount);
    return EncodeMorton2(QuantizeDir(EncodeDir(dir), g) % g);
}
