// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
//
// Custom CS PostProcessing Shader

#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/BlueNoise.ush"

#include "RCHashTable.ush"



// Shader parameters

RWTexture2D<float4> Output;


SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)


[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	
    uint2 PixelId = DispatchThreadId;
	
	// Check that we are in scope
    if (any(float2(DispatchThreadId) >= SceneColorViewport_ViewportSize))
        return;

    float2 UV = (PixelId - SceneColorViewport_ViewportMin) * SceneColorViewport_ViewportSizeInverse;
    FGBufferData GBuffer = GetGBufferData(UV);
    float Depth = ConvertFromDeviceZ(GBuffer.Depth);
    float2 ProbeNDC = ViewportUVToScreenPos(UV);
    float3 ProbeViewPos = float3(ProbeNDC * Depth / float2(View.ViewToClip[0][0], View.ViewToClip[1][1]), Depth);


	Output[PixelId] = float4(ProbeViewPos*0.01,1.0);
}