#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

#include "RCHashTable.ush"


// Shader parameters
RWStructuredBuffer<uint> ActiveProbes;
RWStructuredBuffer<uint> ActiveCounter;

RWStructuredBuffer<uint> TableLastOccupiedFrame;

StructuredBuffer<uint4> TotalRadiance;
StructuredBuffer<uint> Weights;

uint Cascade;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint DispatchThreadId : SV_DispatchThreadID)
{
	uint ProbeId = DispatchThreadId;

	// Check that we are in scope
	if (ProbeId >= ActiveCounter[Cascade - 1])
	{
		return;
	}

	//Split key into higher cascade
	uint64_t ProbeKey = TableKeys[(Cascade - 1) * HashTableSize + ActiveProbes[((Cascade - 1) * HashTableSize) +
		ProbeId]];

	ProbeKeyInfo KeyData = UnpackProbeKey(ProbeKey);

    //Get parent key by halving position
	uint64_t HighKey = PackProbeKey(KeyData.Cell >> 1, KeyData.Level);
    uint Index = HashTableSize;
    if (HashTableAdd(HighKey, Cascade, Index))
	{
		//Update indirect buffer
		uint Counter;
		InterlockedAdd(ActiveCounter[Cascade], 1, Counter);
		ActiveProbes[(Cascade * HashTableSize) + Counter] = Index;
        TableLastOccupiedFrame[(Cascade*HashTableSize)+Index] = View.StateFrameIndex;

    }else
    {
	    //Still update the usage counter
        TableLastOccupiedFrame[(Cascade * HashTableSize) + HashTableFind(HighKey, Cascade)] = View.StateFrameIndex;
    }
}
