#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

#include "RCHashTable.ush"
#include "RCCommon.ush"

//Where in the bigger buffer I cascade's table starts
RWStructuredBuffer<uint> TableStarts;
RWStructuredBuffer<uint> TableLastOccupiedIndex;

RWStructuredBuffer<uint> ActiveProbes;
RWStructuredBuffer<uint> ActiveCounter;

uint NumCascades;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint DispatchThreadId : SV_DispatchThreadID)
{
	uint DataKeyId = DispatchThreadId;

	//Find table
	uint Table = 0;
	for (int i = 0; i < NumCascades; ++i)
	{
        uint TableStart = i * HashTableSize;
		if (DataKeyId >= TableStart)
		{
			Table = i;
		}
		else
		{
			break;
		}
	}
	uint64_t Key = TableKeys[DataKeyId];

	bool Occupied = Key != kInvalidKey;
	if (Occupied)
	{
		//Remove older probes
		if (/*TODO: Lifetime tracking*/ true)
		{
			TableKeys[DataKeyId] = kInvalidKey;
			Occupied = false;
		}
		else
		{
			uint64_t Key = TableKeys[DataKeyId];
			HashTableAddIndex(Key, Table, DataKeyId);
            uint ActiveIndex;
            InterlockedAdd(ActiveCounter[Table], 1, ActiveIndex);
            ActiveProbes[ActiveIndex] = DataKeyId;
        }
	}

	if (!Occupied)
	{
		uint FreeListIndex;
		InterlockedAdd(TableFreeListIndex[Table], 1, FreeListIndex);
        TableFreeList[FreeListIndex] = DataKeyId;
    }
}
