#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

#include "RCHashTable.ush"
#include "RCCommon.ush"

//Where in the bigger buffer I cascade's table starts
RWStructuredBuffer<uint> TableStarts;
RWStructuredBuffer<uint> TableLastOccupiedFrame;

RWStructuredBuffer<uint> ActiveProbes;
RWStructuredBuffer<uint> ActiveCounter;

float HistoryConservation;

RWStructuredBuffer<uint4> TotalRadiance;
RWStructuredBuffer<uint> ProbeWeights;
RWStructuredBuffer<uint> BinCounts;
RWStructuredBuffer<uint> DepositCounts;
uint BaseDirections;

uint NumCascades;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint DispatchThreadId : SV_DispatchThreadID)
{
	uint DataKeyId = DispatchThreadId;

    
    uint BaseTable = DataKeyId / HashTableSize;
    uint Local = DataKeyId - BaseTable * HashTableSize;
    if (BaseTable >= NumCascades || Local >= (HashTableSize >> (2 * BaseTable)))
        return;

	//Find table
	uint Table = 0;
	for (int i = 0; i < NumCascades; ++i)
	{
        uint TableStart = i * HashTableSize;
		if (DataKeyId >= TableStart)
		{
			Table = i;
		}
		else
		{
			break;
		}
	}


	uint64_t Key = TableKeys[DataKeyId];

	bool Occupied = Key != kInvalidKey;
	if (Occupied)
	{
		//Remove older probes
		if (TableLastOccupiedFrame[DataKeyId] < View.StateFrameIndex - 2)
        {
            TableKeys[DataKeyId] = kInvalidKey;
            Occupied = false;

            //Clear probe data
			if (Table == 0)
			{
				BinCounts[DataKeyId] = 0;
			}
            DepositCounts[DataKeyId] = 0;

            uint LocalIndex = DataKeyId - Table * HashTableSize;;
            uint CascadeIndex = Table * HashTableSize * BinsPerProbe(BaseDirections);
            uint Bins = BinsPerProbe(BaseDirections << Table);

            for (int i = 0; i < Bins; ++i)
            {
	            uint SlotIndex = CascadeIndex + LocalIndex * Bins + i;

	            TotalRadiance[SlotIndex] = 0;
                ProbeWeights[SlotIndex] = 0;
            }
        }
		else
		{
			// Surviving probe
			uint64_t Key = TableKeys[DataKeyId];
            uint LocalIndex = DataKeyId - Table * HashTableSize;
            HashTableAddIndex(Key, Table, LocalIndex);
            uint ActiveIndex;
            InterlockedAdd(ActiveCounter[Table], 1, ActiveIndex);
            ActiveProbes[Table*HashTableSize + ActiveIndex] = LocalIndex;
            DepositCounts[DataKeyId] = PackFloatUnsigned(UnpackFloatUnsigned(DepositCounts[DataKeyId]) * HistoryConservation);
        }
	}

	if (!Occupied)
	{
		uint FreeListIndex;
		InterlockedAdd(TableFreeListIndex[Table], 1, FreeListIndex);
        uint LocalIndex = DataKeyId - Table * HashTableSize;
        TableFreeList[FreeListIndex] = LocalIndex;
    }
}
