#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

#include "/Engine/Private/OctahedralCommon.ush"

#include "RCHashTable.ush"
#include "RCCommon.ush"

// Shader parameters
StructuredBuffer<uint> ActiveProbes;
StructuredBuffer<uint> ActiveCounter;

uint Cascade;
uint BaseDirections;
uint NumCascades;

float HistoryConservation;

RWStructuredBuffer<uint4> ProbeRadiance;
RWStructuredBuffer<uint> ProbeWeights;
StructuredBuffer<uint> ProbeDepositCount;

RWStructuredBuffer<float4> ProbeMergedRadiance;

RWTexture2D<float4> FinalIrradiance;
RWStructuredBuffer<uint> ProbeToFinalId; // Converts probe id to finalirradiance tile.
uint FinalAtlasExtend;

groupshared float4 FinalRadiance[32];
groupshared float4 GroupFinalIrradiance[36];
groupshared uint ParentIndices[8];
groupshared float ParentWeights[8];



[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 GroupId : SV_GroupID,
            uint2 GroupThreadId : SV_GroupThreadID)
{
	uint ProbeId = GroupId.x;
	uint Lane = GroupThreadId.y;
	// Check that we are in scope
	if (ProbeId >= ActiveCounter[Cascade])
	{
		return;
	}

	//Blend higher cascade
	uint ProbeIndex = ActiveProbes[Cascade * HashTableSize + ProbeId];
	uint64_t ProbeKey = TableKeys[(Cascade) * HashTableSize + ProbeIndex];
	ProbeKeyInfo KeyData = UnpackProbeKey(ProbeKey);

	int3 ParentCell = (KeyData.Cell - 1) >> 1;
	uint3 Alignment = uint3(~KeyData.Cell & 1);
	uint J = Alignment.x | (Alignment.y << 1) | (Alignment.z << 2);

	//Corner weights for which corners are the closest of the 8, since the child sits either at .75 or .25 on one axis, combined to 3 axi
	static const float CornerWeight[4] = {0.421875, 0.140625, 0.046875, 0.015625};

	uint DirectionCount = BaseDirections << Cascade;

	uint CascadeIndex = Cascade * HashTableSize * BinsPerProbe(BaseDirections);
	uint ParentCascadeIndex = (Cascade + 1) * HashTableSize * BinsPerProbe(BaseDirections);
	uint ParentDirCount = BaseDirections << (Cascade + 1);

	if (Lane < 8)
	{
		//Find parent cells
		uint c = Lane;
		int3 Corner = ParentCell + int3(c & 1, (c >> 1) & 1, c >> 2);

		uint WeightBits = c ^ J;
		uint WeightId = countbits(WeightBits);
		float InterpWeight = CornerWeight[WeightId];

		uint64_t CascadeKey = PackProbeKey(Corner, KeyData.Level);

		uint ParentIndex = HashTableFind(CascadeKey, Cascade + 1);
		if (ParentIndex < HashTableSize)
		{
			//Amount of rays this probe got, so lower ones are low quality
			uint DepositCount = ProbeDepositCount[((Cascade + 1) * HashTableSize) + ParentIndex];
			if (DepositCount <= 0)
			{
				ParentIndices[c] = HashTableSize;
				ParentWeights[c] = 0;
			}
			else
			{
				float DepositQuality = UnpackFloatUnsigned(DepositCount);
				float QualityInterpWeight = InterpWeight * DepositQuality;
				ParentIndices[c] = ParentIndex;
				ParentWeights[c] = QualityInterpWeight;
			}
		}
		else
		{
			ParentIndices[c] = HashTableSize;
			ParentWeights[c] = 0;
		}
	}

	//Wait untill all probes are found/loaded
	GroupMemoryBarrierWithGroupSync();


	uint Bins = BinsPerProbe(DirectionCount);
	//Go over all the bins, each groupthread handles 1/32 bins, merging via lanes
	for
	(
		int i = 0;
		i < Bins;
		i
		+=
		32
	)
	{
		uint Bin = i + Lane;

		//Load own Radiance
		uint SlotIndex = CascadeIndex + ProbeIndex * Bins + Bin;

		float Weight = UnpackFloatUnsigned(ProbeWeights[SlotIndex]);
		uint4 PackedRadiance = ProbeRadiance[SlotIndex];
		float4 UnpackedRadiance = float4(UnpackFloatUnsigned(PackedRadiance.x), UnpackFloatUnsigned(PackedRadiance.y),
		                                 UnpackFloatUnsigned(PackedRadiance.z), UnpackFloatUnsigned(PackedRadiance.w));
		float3 CurrentRadiance = UnpackedRadiance.xyz / Weight;
		float TransmittedWeight = UnpackedRadiance.w / Weight;

		float4 ParentRadianceSum = 0;
		float ParentRadianceWeight = 0;
		if (Cascade < NumCascades - 1)
		{
			for (uint c = 0; c < 8; ++c)
			{
				uint ParentIndex = ParentIndices[c];
				if (ParentIndex < HashTableSize)
				{
					float ParentWeight = ParentWeights[c];

                    uint ParentSlotIndex = ParentCascadeIndex / 4 + ParentIndex * Bins + Bin;
					float4 DirRadiance = ProbeMergedRadiance[ParentSlotIndex];
					if (DirRadiance.w > 0.0)
					{
						ParentRadianceSum += DirRadiance * ParentWeight;
						ParentRadianceWeight += ParentWeight;
					}
				}
			}
		}
        float4 ParentRadiance = ParentRadianceWeight > 0.0001 ? (ParentRadianceSum / ParentRadianceWeight) : 0;
        float3 ParentRadApplied = ParentRadiance.w > 0.0001 ? ParentRadiance.xyz / ParentRadiance.w : 0;
        float4 Radiance = (Weight > 0.0001)
			                  ? 
			                  float4(CurrentRadiance + ParentRadApplied *
			                           TransmittedWeight, 1) : 0;
		//Output final buffer for final cascade for apply pass
		if (Cascade == 0)
		{
			//Merge all the direction bins into an octehedral map, avoids apply sampling all bins
			FinalRadiance[Lane] = Radiance;
            GroupMemoryBarrierWithGroupSync();

            for (uint t = Lane; t < (6*6); t += 32)
            {
                float2 Oct = ((float2(t % 6, t / 6) + 0.5) / 6.0) * 2.0 - 1.0;
                float3 Normal = OctahedronToUnitVector(Oct);

                float4 Acc = 0;
                for (uint SampleBin = 0; SampleBin < 32; ++SampleBin)
                {
                    float Cos = max(0, dot(LinearToDir(SampleBin, BaseDirections), Normal));
                    float4 Rad = FinalRadiance[SampleBin];
                    if (Rad.w > 0)
                        Acc += float4(Rad.xyz * Cos, Cos);
                }
                GroupFinalIrradiance[t] = Acc;
            }
            GroupMemoryBarrierWithGroupSync();

            //Active(dense) list index since output is dense.
            uint TextureTile = ProbeId;
            //1 writes map
			if (Lane == 0)
            {
	            ProbeToFinalId[ProbeIndex] = TextureTile;
            }

            uint2 Origin = uint2(TextureTile % FinalAtlasExtend, TextureTile / FinalAtlasExtend) * 8; // 8 is the 6x6 map plus a border for interp
            for (uint p = Lane; p < (8*8); p += 32)
            {
                int2 Pixel = int2(p & 7, p >> 3);
                //without border
                int2 InsidePixel = Pixel - 1;

                bool BorderX = InsidePixel.x < 0 || InsidePixel.x > 5;
                bool BorderY = InsidePixel.y < 0 || InsidePixel.y > 5;
                int2 Clamped = clamp(InsidePixel, 0, 5);
				//Flip/Wrap at border
                if (BorderX && BorderY)
                    Clamped = 5 - Clamped;
                else if (BorderX)
                    Clamped.y = 5 - Clamped.y;
                else if (BorderY)
                    Clamped.x = 5 - Clamped.x;
                FinalIrradiance[Origin + Pixel] = GroupFinalIrradiance[Clamped.y * 6 + Clamped.x];
            }
        }

		//Merge the 4 direction bins into 1 across lanes
		uint L = WaveGetLaneIndex();
		float4 LaneMergedRadiance = Radiance;
		LaneMergedRadiance += WaveReadLaneAt(LaneMergedRadiance, L ^ 1);
		LaneMergedRadiance += WaveReadLaneAt(LaneMergedRadiance, L ^ 2);
		if (Lane % 4 == 0)
		{
			ProbeMergedRadiance[(CascadeIndex + ProbeIndex * Bins) / 4 + Bin / 4] = LaneMergedRadiance.w > 0.0
				? float4(LaneMergedRadiance.xyz / LaneMergedRadiance.w, 1.0)
				: 0;
		}


		//Reinsert own radiance with temporal decay
		ProbeWeights[SlotIndex] = PackFloatUnsigned(Weight * HistoryConservation);
		UnpackedRadiance *= HistoryConservation;
		ProbeRadiance[SlotIndex] = uint4(PackFloatUnsigned(UnpackedRadiance.x), PackFloatUnsigned(UnpackedRadiance.y),
		                                 PackFloatUnsigned(UnpackedRadiance.z), PackFloatUnsigned(UnpackedRadiance.w));
	}
}
