#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

#include "RCHashTable.ush"


// Shader parameters
StructuredBuffer<uint> PrevActiveProbes;
StructuredBuffer<uint> PrevActiveCounter;
StructuredBuffer<uint> ActiveProbes;
StructuredBuffer<uint> ActiveCounter;

StructuredBuffer<uint64_t> PrevHashTable;

StructuredBuffer<uint64_t> HashTable;
RWStructuredBuffer<uint64_t> RWHashTable;
uint HashTableSize;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint DispatchThreadId : SV_DispatchThreadID)
{
	
    uint ProbeId = DispatchThreadId;
	
	// Check that we are in scope
    if (ProbeId >= PrevActiveCounter[0])
        return;


    //Split key into higher cascade
    uint64_t ProbeKey = PrevHashTable[PrevActiveProbes[ProbeId]];
    ProbeKeyInfo KeyData = UnpackProbeKey(ProbeKey);
    HashTableData Table = HashTableData{
	    HashTable, RWHashTable, HashTableSize
    };

    uint64_t HighKey = PackProbeKey(KeyData.Cell >> 1, KeyData.Level, Table);
    //Index to keep things seperate avoiding conflicts
    uint Index = MurmurFinalize32(uint(HighKey) ^ uint(HighKey >> 32));
	HashTableAdd(HighKey, Index);
    uint Counter;
    InterlockedAdd(ActiveCounter[0], 1, Counter);
    ActiveProbes[Counter] = Index;

}
