#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/BlueNoise.ush"

#include "RCHashTable.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"
#include "RCCommon.ush"

// Shader parameters
RWTexture2D<float4> Output;

StructuredBuffer<uint4> ProbeRadiance;
StructuredBuffer<uint> ProbeWeights;

SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)] 
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	
    uint2 PixelId = DispatchThreadId;
	
	// Check that we are in scope
    if (any(float2(DispatchThreadId) >= SceneColorViewport_ViewportSize))
        return;

    float2 ViewportUV = (float2(PixelId) + 0.5f) * SceneColorViewport_ViewportSizeInverse;
    float2 BufferUV = (float2(PixelId) + 0.5f + SceneColorViewport_ViewportMin) * SceneColorViewport_ExtentInverse;

    float DeviceZ = LookupDeviceZ(BufferUV);
    if (DeviceZ == 0)
        return;
    float2 ScreenPos = ViewportUVToScreenPos(ViewportUV);
    float3 TranslatedWorldPos = SvPositionToTranslatedWorld(float4(float2(PixelId) + 0.5f + SceneColorViewport_ViewportMin, DeviceZ, 1.0f));

    float3 WorldPos = DFFastSubtractDemote(TranslatedWorldPos, PrimaryView.PreViewTranslation);
    float3 CameraPos = DFHackToFloat(PrimaryView.WorldCameraOrigin);
    
    uint64_t Key = MakeProbeKey(WorldPos, CameraPos);
    uint Index = 0;
    if (HashTableFind(Key, Index))
    {
        float3 TotalRadiance = 0;
        uint Total = 0;
        //Dumbly add all directions
        for (uint i = 0; i < BinsPerProbe(); ++i)
        {
            uint BuffIndex = Index * BinsPerProbe() + i;
            uint Weight = ProbeWeights[BuffIndex];
            if (Weight == 0)
            {
	            continue;
            }
            uint4 Radiance = ProbeRadiance[BuffIndex];
            float3 FloatRad = float3(UnpackFloatUnsigned(Radiance.x), UnpackFloatUnsigned(Radiance.y), UnpackFloatUnsigned(Radiance.z));
        	TotalRadiance += FloatRad / float(Weight);
            Total++;
        }
        FGBufferData GBufferData = GetGBufferData(BufferUV);
        Output[PixelId] += float4(Total ? (TotalRadiance / float(Total))*GBufferData.BaseColor : 0, 1);
    }
}