// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;

Texture2D<float4> ProbeCascade;

// SceneColor Viewport parameters
SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

// Output
RWTexture2D<float4> Output;

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	// Check that we are in scope
    if (any(DispatchThreadId >= SceneColorViewport_ViewportMax))
    {
        return;
    }
	
    // Calculate SampleUV with viewport parameters
    float2 sampleUV = (float2(SceneColorViewport_ViewportMin) + (DispatchThreadId + 0.5)) * SceneColorViewport_ExtentInverse;
    
    //Sample probe
    float4 ProbeColor = ProbeCascade.SampleLevel(GlobalBilinearClampedSampler, sampleUV, 0);
    FGBufferData GBuffer = GetGBufferData(sampleUV);

    // Write output, apply as lighting multiplying by diffuse
    Output[SceneColorViewport_ViewportMin + DispatchThreadId] = float4(ProbeColor.rgb * GBuffer.DiffuseColor,1.0);
}