// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;

Texture2D<float4> ProbeCascade;

// SceneColor Viewport parameters
SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

// Output
RWTexture2D<float4> Output;

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	// Check that we are in scope
    if (any(DispatchThreadId >= SceneColorViewport_ViewportMax))
    {
        return;
    }
	
    // Calculate SampleUV with viewport parameters
    float2 sampleUV = (float2(SceneColorViewport_ViewportMin) + (DispatchThreadId + 0.5)) * SceneColorViewport_ExtentInverse;
    
    //Sample probe
    float4 ProbeColor = ProbeCascade.SampleLevel(GlobalBilinearClampedSampler, sampleUV, 0);
    //ProbeColor += ProbeCascades.SampleLevel(GlobalBilinearClampedSampler, float3((float2(SceneColorViewport_ViewportMin) + (DispatchThreadId + 0.5)) * SceneColorViewport_ExtentInverse * 0.5, 1), 0);

    float4 SceneColor = OriginalSceneColor.SampleLevel(GlobalBilinearClampedSampler, sampleUV, 0);

    // Write output
    Output[SceneColorViewport_ViewportMin + DispatchThreadId] = ProbeColor;
}