// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;

RWTexture2DArray<float4> ProbeCascades;

SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)
uint Cascade;

static const int BaseRayCount = 8;

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
    uint2 PixelId = DispatchThreadId * pow(2,Cascade)+ SceneColorViewport_ViewportMin;
	// Check that we are in scope
    if (any(PixelId >= SceneColorViewport_Extent))
    {
        return;
    }
	
    // Calculate SampleUV with viewport parameters
    float2 StartUV = (float2(PixelId) + 0.5) * SceneColorViewport_ExtentInverse;

    int RayCount = pow(BaseRayCount, 1+Cascade);

    float Partial = 0.125;
    float IntervalStart = RayCount == BaseRayCount ? 0.0 : Partial;
    float IntervalEnd = RayCount == BaseRayCount ? Partial : sqrt(2.0);

    float4 Radiance = float4(0.0, 0.0, 0.0, 0.0);

    //March SceneColor
    for (int i = 0; i < RayCount; i++)
    {
        float Index = float(i);
	    // Add 0.5 radians to avoid vertical angles
        float AngleStep = (Index + 0.5);
        float Angle = ((2 * PI) / RayCount) * AngleStep;
        float2 RayDirection = float2(cos(Angle), -sin(Angle));

	    // Start in our decided starting location
		// Keep track of how far we've gone
        float Traveled = IntervalStart;
        float4 RadDelta = float4(0.0, 0.0, 0.0, 0.0);

       //March the texture
        int MaxSteps = SceneColorViewport_Extent.x;

        for (int Step = 1; Step < MaxSteps; Step++)
        {

		    // Go the direction we're traveling
            float2 SampleUv = StartUV + RayDirection * Traveled * (SceneColorViewport_Extent.y / float(SceneColorViewport_Extent.x));

            if (any(SampleUv >= SceneColorViewport_UVViewportMax) || any(SampleUv <= SceneColorViewport_UVViewportMin))
            {
                break;
            }
            float4 ColorSample = OriginalSceneColor.SampleLevel(GlobalBilinearClampedSampler, SampleUv, 0);
			//Hardcoded "hit"
            if (ColorSample.r > 0.0 || ColorSample.b > 0)
            {
                RadDelta += float4(0, 0, ColorSample.b, 1.0);
                break;
            }
	    	// Stop if we've gone our interval length!
            Traveled += float2(SceneColorViewport_ExtentInverse).x;
            if (Traveled >= IntervalEnd)
            {
                break;
            }
        }
		// Accumulate total radiance
        Radiance += RadDelta;
    }
    float4 Output = Radiance / RayCount;

    ProbeCascades[uint3(DispatchThreadId+SceneColorViewport_ViewportMin, Cascade)] = Output;
}