#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/BlueNoise.ush"

#include "RCHashTable.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"


// Shader parameters
RWTexture2D<float4> Output;

StructuredBuffer<uint64_t> Probes;
RWStructuredBuffer<uint64_t> RWProbes;

RWStructuredBuffer<uint> ActiveProbes;
RWStructuredBuffer<uint> ActiveCounter;

SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

//Hash to color debug


[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	
    uint2 PixelId = DispatchThreadId;
	
	// Check that we are in scope
    if (any(float2(DispatchThreadId) >= SceneColorViewport_ViewportSize))
        return;

    float2 ViewportUV = (float2(PixelId) + 0.5f) * SceneColorViewport_ViewportSizeInverse;
    float2 BufferUV = (float2(PixelId) + 0.5f + SceneColorViewport_ViewportMin) * SceneColorViewport_ExtentInverse;

    float DeviceZ = LookupDeviceZ(BufferUV);
    if (DeviceZ == 0)
        return;
    float3 TranslatedWorldPos = SvPositionToTranslatedWorld(float4(float2(PixelId) + 0.5f + SceneColorViewport_ViewportMin, DeviceZ, 1.0f));

    float3 WorldPos = DFFastSubtractDemote(TranslatedWorldPos, PrimaryView.PreViewTranslation);
    float3 CameraPos = DFHackToFloat(PrimaryView.WorldCameraOrigin);
    
	uint64_t Key = MakeProbeKey(WorldPos, CameraPos);
	//Index to keep things seperate avoiding conflicts
    uint Index = 0;
    //MurmurFinalize32(uint(Key) ^ uint(Key >> 32));

		//Try add to table
        if (HashTableAdd(Key, Index, 0))
        {
	        //Add to active probes for next passes
	        uint Counter;
	        InterlockedAdd(ActiveCounter[0], 1, Counter);
	        ActiveProbes[Counter] = Index;
        }

}